### ISSUE TITLE
Add packages from esnext-showcase?

### ISSUE THREAD

**Issue by sudodoki** [mikaelbr/proxy-fun#2]
Hi!

There is a [list of packages](https://github.com/sindresorhus/esnext-showcase) some of which are featuring proxies - might want to add those.

**Comment by mikaelbr** [comment]
Brilliant! Thanks.

I did not know about https://github.com/mathiasbynens/tpyo. I had a [similar idea](https://github.com/mikaelbr/proxy-fun/blob/master/examples/api-distance/index.js) and felt really clever about it. But, of course, I should know there's no such thing as an original idea.
