### ISSUE TITLE
Consider adding react-easy-state, the observer utility (and the compiler utility)

### ISSUE THREAD

**Issue by solkimicreb** [mikaelbr/proxy-fun#21]
- [React Easy State](https://github.com/solkimicreb/react-easy-state) is a transparent state management library for React.

- [The Observer Utility](https://github.com/nx-js/observer-util) is a general purpose transparent reactivity library (React Easy State is just a thin wrapper of it). It uses ES6 Proxies to achieve a 100% language coverage for reactivity.

- [The Compiler Utility](https://github.com/nx-js/compiler-util) is a 'sandboxed' code evaluation library. It uses ES6 Proxies (has traps) in conjuction with the `with` keyword to 'sandbox' code. This library gets less dev time from me than the former two nowadays.

Please add the ones you like from these. Thanks! 🙂

**Comment by mikaelbr** [comment]
Thanks! Added no! 🎉

**Comment by solkimicreb** [comment]
Thanks 🙂
