### ISSUE TITLE
Safe Navigation

### ISSUE THREAD

**Issue by dakaraphi** [mikaelbr/proxy-fun#7]
Example using proxies for safe navigation or null conditional operators
https://gist.github.com/dakaraphi/6a87168db66fd8f032d2

**Comment by mikaelbr** [comment]
Thanks! I'm adding it now. I've also been thinking about doing something like a lazy JSON-compatible data. Or even lazy from the server. While traversing the structure you can create an internal key path and look up that on a graph like server siden component and fill the object you are traversing. Maybe not very useful in all cases, but I think it would be a interesting case study.
