### ISSUE TITLE
Package Suggestion – Stroxy (Event-Streams from native Events)

### ISSUE THREAD

**Issue by nilssolanki** [mikaelbr/proxy-fun#8]
I wrote a little library, similar to bacon.js, which proxies native event methods (E.g. `document.body.addEventListener('click');`) and returns a pipeable stream.
https://github.com/nilssolanki/stroxy

**Comment by mikaelbr** [comment]
Thank you! I will update the repo when I get home from my vacation and get access to a computer. You can also send a PR and I'll merge it from the beach. :sunny:

**Comment by nilssolanki** [comment]
That you, I just did. Enjoy your vacation!

**Comment by mikaelbr** [comment]
Thanks! Merged it now
